import Head from 'next/head'

/* Generated from PRIVACY-POLICY.md. Edit the Markdown source and regenerate
   rather than editing this file by hand. */

const CONTENT = `<h1>Privacy Policy</h1>
<p><strong>Bravo</strong></p>
<p><strong>Effective date:</strong> September 1, 2026 <strong>Last updated:</strong> September 1, 2026</p>
<p><strong>Talk with Bravo, LLC</strong> 10178 Foxridge Circle, Highlands Ranch, CO 80126, USA admin@talkwithbravo.com</p>
<hr />
<h2>The short version</h2>
<p>Bravo helps people communicate. To suggest words and phrases that fit the person using it, we store a profile you build — things like favorite topics, the names of family and friends, places, and activities — and we send relevant parts of it, along with what is being typed, to an AI provider that generates suggestions.</p>
<ul><li><strong>The profile is entirely optional.</strong> Bravo works fully without it — you can use it and tell us nothing about the person using it.</li><li><strong>We do not sell your information, and we never have.</strong></li><li><strong>We do not use your information to train AI models</strong>, and our AI provider is contractually prohibited from using it to train theirs.</li><li><strong>We do not show ads</strong> and there is no advertising or tracking technology in the app.</li><li><strong>We do not share your information with anyone except</strong> the service providers listed in Section 5 and the people <em>you</em> choose to give access to.</li><li><strong>You can see, correct, export, and delete everything</strong>, at any time.</li></ul>
<p>This app is used by children. If you are a parent or guardian setting it up, Section 7 is written for you and explains exactly what we collect about your child and how to control it.</p>
<hr />
<h2>1. Who this policy covers</h2>
<p>This policy explains how Talk with Bravo, LLC ("we," "us") handles personal information across all of Bravo — the <strong>web application</strong> at https://app.talkwithbravo.com, the <strong>iOS app</strong>, the <strong>Android app</strong>, and the services behind them. It is a single policy covering every platform; where something differs by platform, we say so. It applies to:</p>
<ul><li>the <strong>account holder</strong> — the adult who creates the account (a user, parent, guardian, or caregiver);</li><li>the <strong>communicator</strong> — the person who uses the app to communicate, who may be the account holder, a child, or another supported person; and</li><li><strong>people named in a profile</strong> — family, friends, and others whose names appear as context.</li></ul>
<p>Our End User License Agreement is at https://talkwithbravo.com/eula. This policy forms part of it.</p>
<h2>2. What we collect</h2>
<p>We collect only what the app needs to work. The only third-party component in the app is Firebase Authentication, which signs you in. There is <strong>no analytics SDK, no crash-reporting SDK, no advertising SDK, and no tracking technology of any kind</strong> in Bravo.</p>
<p><strong>Account information.</strong> We use <strong>Firebase Authentication</strong>, a Google service, to create and secure accounts. When the account holder signs up or signs in, Firebase collects and stores on our behalf: the <strong>email address</strong>, a <strong>unique account identifier</strong>, and, for security purposes, the <strong>IP address</strong>, device and browser information, and the times the account was created and last used. <strong>We do not ask for the account holder's name.</strong> You sign in with an email address and a password. Passwords are stored by Firebase in hashed and salted form; we never see or store your password. <strong>We do not offer sign-in through Apple, Google, Facebook, or any other third-party identity provider</strong>, so no such provider learns that you use Bravo.</p>
<p>We use account information to create and secure the account, to keep you signed in, to detect and prevent unauthorized access, and to contact you about the service. We do not use it for marketing.</p>
<p><strong>Profile and personalization context.</strong> Information you choose to enter so suggestions fit the communicator: preferred name, favorite topics and interests, <strong>names, relationships, and birthdays of family and friends</strong>, places the communicator goes, routines and activities, and vocabulary you add or customize.</p>
<p><strong>The communicator's date of birth</strong>, if you provide it, is used to suggest language that suits their age — a seven-year-old and an adult asking for the same thing should not be handed the same words. We keep <strong>only the month and day for family and friends</strong>, since the year serves no purpose there.</p>
<p><strong>This can include information about the communicator's disability or how they communicate</strong>, if you choose to provide it — because suggestions that suit one person may be wrong for another, and knowing something about how someone communicates is often what makes the difference between useful and useless. <strong>You never have to provide it.</strong> If you do, we treat it as sensitive: it is used only to generate suggestions, it is never shared beyond the service providers in Section 5, and you can remove it at any time.</p>
<p><strong>Safety information is different, and always applies.</strong> Some of what you can record is there to keep the communicator safe rather than to personalize anything: <strong>allergies</strong>, and the physical or communication limitations you note — for example that someone does not eat by mouth. <strong>We always take these into account, even when personalized suggestions are turned off.</strong> Turning personalization off should not mean Bravo starts offering food someone is allergic to, or actions they cannot safely do. This information is used for that purpose only and for nothing else.</p>
<p><strong>All of this is optional.</strong> The app works without it; suggestions are simply more generic. You choose what to enter, and you can edit or remove any of it at any time.</p>
<p><strong>Information the app learns — off unless you turn it on.</strong> Bravo can notice preferences from what the Communicator says and suggest saving them to the Profile. If someone asks the Communicator their favorite food and they answer, the app can propose saving a short note — "favorite food: pizza" — so later suggestions fit them better. We save a <strong>brief summary, not a recording or a transcript</strong>.</p>
<p>Two things make this different from how most apps handle it:</p>
<ul><li><strong>It is off by default.</strong> Nothing is learned unless you switch it on.</li><li><strong>Nothing is saved without a person approving it.</strong> When the app notices something, it asks. You choose to save it or not. The app never adds to a Profile on its own.</li></ul>
<p>You are always in control:</p>
<ul><li>Everything saved this way is listed in Admin Toolbar → User Info Admin, labeled as learned rather than entered, so you can tell the difference at a glance.</li><li>You can <strong>edit or delete any learned item</strong>, individually or all at once.</li><li>You can <strong>turn learning off</strong> at any time and keep everything already saved, or delete it all.</li></ul>
<p><strong>There are limits on what the app will ever work out on its own.</strong> It will not draw conclusions about health conditions, symptoms, medications, disability, mental or emotional state, religion, race or ethnicity, sexual orientation, immigration status, or political views. It will not record negative things said about a named person. It notices everyday preferences — foods, activities, places, interests, people enjoyed — and nothing else.</p>
<p><strong>This is a limit on inference, not on you.</strong> If you choose to enter information about your child's disability or how they communicate, we store what you tell us (see "Profile and personalization context" above). The distinction is that <strong>you decide what we know; the app never decides for you.</strong></p>
<p><strong>Communication content.</strong> Words, phrases, and messages composed in the app, and the suggestions generated in response, to the extent needed to provide the feature and to keep the communicator's own saved content available to them.</p>
<p><strong>What gets used, and what gets said.</strong> We keep a record of the buttons and pages used, <strong>and of the words and phrases spoken through the app</strong>, each with the time it happened. So the record shows not only that the "Places" category was opened, but what was said next.</p>
<p>This is what makes the activity reports useful: it lets you — or a speech-language pathologist you have given access to under Section 5.3 — see how communication is developing, which parts of the vocabulary are working, and whether the pages you have set up are actually being found and used.</p>
<p><strong>We want to be plain about this</strong>, because it is more than most apps record. It is a record of what the communicator said, not a count of taps. We do not use it to build a picture of their life, we do not share it beyond the people you have granted access to, and <strong>you can switch it off at any time in Admin Toolbar → User Info Admin</strong>. Turning it off stops new records; existing ones can be deleted along with the rest of the profile data. These records are kept for <strong>180 days</strong> and then deleted automatically. See Section 7.5.</p>
<p><strong>Support information.</strong> If you contact us, the messages you send us and what you tell us about the problem.</p>
<p><strong>Technical information.</strong> Basic information needed to operate and secure the service: the app version, the operating system and browser you are using, and server logs that record the IP address, the time of the request, and which part of the service was requested. We use this to keep the service running and to investigate faults and abuse, not to build a profile of you.</p>
<p><strong>Cookies and local storage.</strong> In the web application we use browser storage only for things that are strictly necessary: keeping you signed in, and remembering your settings. Firebase Authentication stores a session token in your browser for this purpose. <strong>We use no advertising cookies, no analytics cookies, and no third-party trackers</strong>, so there is no tracking for you to opt out of. Clearing your browser storage signs you out.</p>
<p><strong>Images you upload.</strong> You can upload your own pictures to use on buttons instead of a symbol from our library, and to set a profile picture or a mood image. <strong>These are often photographs of the communicator, their family, or places they know</strong>, which is what makes them useful.</p>
<ul><li>We store them in Google Cloud Storage, in the region described in Section 11.</li><li>They are kept until you delete them, or until the profile or account is deleted, and are included in the deletion described in Section 7.5 and Section 10.</li><li>They are included in the copy of your information you can download at any time.</li><li><strong>We do not use uploaded images to train any AI model</strong>, and we do not send them to our AI provider.</li></ul>
<p><strong>Only upload pictures you are entitled to use</strong>, and think carefully before uploading a photograph of someone who has not agreed to it. See Section 3.</p>
<p><strong>Pictures Bravo creates.</strong> Bravo can draw an illustration for a story or a document the communicator has written. To do that, <strong>a summary of what they wrote is sent to Google</strong>, which returns a picture, as described in Section 5. The picture that comes back is a depiction of their own writing, so we treat it as their content, not as artwork of ours:</p>
<ul><li>it is stored privately and is only viewable from the account that made it;</li><li>it is deleted with the profile or account, and appears in the copy of your information you can download; and</li><li><strong>we do not use it, or the writing it came from, to train any AI model.</strong></li></ul>
<p>The symbols and pictures that come with Bravo are different — those are our own artwork, shared by everyone, and contain nothing about any communicator.</p>
<p><strong>Microphone and spoken input.</strong> Bravo can be used hands-free: the app listens for a wake word and then takes the question or comment that follows. <strong>Listening begins automatically when a listening screen is opened, if you have granted microphone permission</strong>, and continues while that screen is in use. This needs explaining carefully, because more than one party is involved.</p>
<p><strong>Bravo does not do the speech recognition itself.</strong> It uses the speech recognition built into your browser, phone, or tablet. Two separate things are listened for, and <strong>we treat them differently on purpose</strong>.</p>
<p><strong>Listening for the wake word.</strong> This is the part that runs continuously, so it is the part we work hardest to keep on your device.</p>
<ul><li><strong>In the iOS and Android apps</strong>, Bravo asks the operating system to recognize the wake word <strong>on the device itself, without sending any audio anywhere</strong>. Where the device supports this, no audio leaves it at all. Not every device can do it — support depends on the model, the operating system version, and the language — and where it cannot, the audio is sent to Apple or Google to be turned into text, exactly as described below. <strong>The app shows you which of these is happening on your device</strong>, under <strong>Speech recognition</strong> in the app's admin settings.</li><li><strong>On the web</strong>, the browser performs the recognition. In Chrome, Edge, and Safari that means the audio is sent to the browser maker's speech service.</li></ul>
<p>Because the app must recognize what it hears in order to notice the wake word, speech near the device is being converted to text throughout — including speech from people other than the communicator, and speech never meant for the app. Only the words after the wake word are used. Everything else is discarded as soon as it is checked.</p>
<p><strong>Listening for your question.</strong> Once the wake word is heard, what you say next <strong>is sent to Apple or Google to be turned into text</strong>, on every platform, so that it is transcribed accurately. This is a deliberate act by the person using the app, rather than continuous background listening, which is why we treat it differently.</p>
<p><strong>In both cases we never receive the audio and never store it.</strong> Where audio does leave your device, it goes to the browser maker or the operating system maker, and what they do with it is governed by <strong>their</strong> privacy policy, not ours.</p>
<p><strong>What Bravo does with the text.</strong> Once the wake word is heard, the words that follow are treated exactly like text typed into the app:</p>
<ul><li>they are sent to Google to generate a suggestion, as described in Section 5; and</li><li><strong>if the guardian has turned activity logging on</strong>, the question and the response are saved to the activity log described above and deleted after 180 days. If activity logging is off, the text is used to generate the suggestion and then discarded.</li></ul>
<p><strong>If you would rather none of this happen, refuse microphone permission, or withdraw it in your browser, phone, or tablet settings.</strong> That stops the listening entirely and is currently the control that governs it. Everything else in Bravo works normally without the microphone; only hands-free use is lost. No other feature of Bravo sends anything to a speech service.</p>
<p><strong>What we do not collect:</strong> we do not collect device location from your phone's or browser's location services, we do not access your contacts or health data, and we do not use any advertising identifier. <strong>We do not read your photo library</strong> — when you upload a picture, the phone or browser shows you a picker and gives us only the single image you choose. "Location" in a profile means only a place <em>you typed in</em> as context — for example "Grandma's house" or "school."</p>
<h2>3. Information about other people</h2>
<p>When you add a family member's or friend's name to a profile, you are giving us information about someone who is not our user. We use it for one purpose only: helping the AI generate relevant suggestions for the communicator. We do not build profiles of those people, do not contact them, and do not combine their names with information from any other source.</p>
<p>Please add only what is genuinely useful — first names and relationships are usually enough, and we ask that you not enter other people's addresses, phone numbers, health details, or other sensitive information about them. Anyone named in a profile may contact us at admin@talkwithbravo.com to ask what we hold about them and to have it removed.</p>
<p><strong>Speech picked up by the microphone.</strong> If hands-free use is switched on, speech from other people near the device is transcribed by the browser's speech service in order to detect the wake word, as described in Section 2. Bravo keeps none of it unless it follows the wake word. Please tell anyone who is regularly nearby that the feature works this way, and switch it off in settings if that is not appropriate for your household or classroom.</p>
<h2>4. How we use information</h2>
<p>We use personal information to:</p>
<ul><li>generate communication suggestions tailored to the communicator;</li><li>create, secure, and administer accounts;</li><li>save profiles, vocabulary, and settings so they are available across sessions and devices;</li><li>provide support when you ask for it;</li><li>keep the service secure, detect abuse, and enforce our EULA; and</li><li>comply with law.</li></ul>
<p><strong>We do not</strong> sell personal information. <strong>We do not</strong> share it for cross-context behavioral advertising. <strong>We do not</strong> use it for advertising or marketing profiling. <strong>We do not</strong> use it to train, fine-tune, or improve any AI model — ours or anyone else's.</p>
<h2>5. How AI suggestions work, and who receives information</h2>
<h3>5.1 What is sent, and to whom</h3>
<p>To generate suggestions, the app sends the text being composed together with relevant personalization context from the profile to <strong>Google LLC</strong>, which processes it through its Vertex AI service and returns suggestions. The same route is used when Bravo draws an illustration for something the communicator has written: a summary of the writing is sent, and a picture comes back.</p>
<p>Google acts as our service provider under a written agreement that requires it to use the information <strong>only to provide the service to us and only on our instructions</strong>, and <strong>prohibits it from using the information to train or improve its models</strong>.</p>
<p>It may not pass the information on to anyone else, with two ordinary exceptions: its own service providers, who are bound by equivalent obligations, and disclosures required by law. A current list of those service providers is published by Google and linked from https://talkwithbravo.com/notices.</p>
<p><strong>About temporary storage.</strong> To make suggestions faster and cheaper to generate, we ask Google to hold a copy of the <strong>stable</strong> parts of the profile for a short period, so we don't have to resend them with every request. That means the profile information described in Section 2 — including anything you have told us about the communicator — and the summary of preferences the app has saved.</p>
<p><strong>Actual conversation is never held this way.</strong> Messages, mood, current activity, and diary entries are sent fresh with each request and discarded once the suggestion is returned.</p>
<p>This is storage we create and control:</p>
<ul><li>it expires automatically after <strong>4 hours</strong>;</li><li>we can delete it at any time, and we do so immediately when you delete a profile or account; and</li><li>it is used only to answer our own requests for your suggestions, never for anything else.</li></ul>
<p>Suggestions are generated automatically. No human at Talk with Bravo, LLC or at Google reads communication content in the ordinary course of providing the service.</p>
<h3>5.2 Hosting and account infrastructure</h3>
<p><strong>Google</strong> provides our infrastructure in two ways, in both cases as our service provider, processing data only on our instructions and not for its own purposes:</p>
<ul><li><strong>Google Cloud Platform</strong> stores accounts, profiles, and saved content in <strong>us-central1</strong> in the United States.</li><li><strong>Firebase Authentication</strong> handles sign-in and stores the account information described in Section 2.</li><li><strong>Vertex AI</strong> generates the suggestions. Requests to it are handled by Google's global service, which means <strong>the processing itself may take place at a Google facility outside the United States</strong>, wherever capacity is available at that moment. Your stored information stays in the United States; it is the momentary processing that may not. Google remains bound by the same contractual limits wherever it happens.</li></ul>
<p>Google does not use this information to build advertising profiles, and we do not use any Google analytics or advertising product in Bravo.</p>
<p>When an account is deleted, authentication records are removed from Google's live systems promptly and from its backup systems within the period Google documents for that service (see Section 7.5).</p>
<h3>5.3 People you give access to</h3>
<p>You control these, and each one is off unless you turn it on:</p>
<ul><li><strong>A designated speech-language pathologist (SLP) or other supporter.</strong> You may grant a named person access to a profile so they can help configure vocabulary and support the communicator. They see what you grant them. <strong>You can revoke access at any time in Admin Toolbar → User Info Admin</strong>, and we will show you who currently has access.</li><li><strong>Bravo support.</strong> If you ask us for help and we need to see your profile to diagnose the problem, you can grant our support team temporary access. <strong>We do not access your profile content unless you grant this</strong>, access is limited to the staff handling your request, and you can revoke it at any time.</li></ul>
<h3>5.4 Other disclosures</h3>
<p>We may disclose information if required by law, valid legal process, or to protect the safety of a user or the public. If we are ever legally compelled to disclose information about a user, we will notify the account holder unless prohibited from doing so.</p>
<p>If we are involved in a merger, acquisition, or sale of assets, personal information may transfer as part of that transaction. We will notify you beforehand, and any successor will be bound by commitments no less protective than those in this policy.</p>
<p><strong>That is the complete list of who receives personal information.</strong> We have no other recipients, no data brokers, no advertising partners, and no analytics vendors.</p>
<h2>6. Legal bases and your consent</h2>
<p>We rely on your consent to collect and use profile and personalization context, and on the necessity of processing to provide the service you have asked for. Where we ask for consent, you may withdraw it at any time — see Section 9.</p>
<h2>7. Children's privacy</h2>
<p><strong>This section is written for parents and guardians, and it governs if it conflicts with anything else in this policy.</strong></p>
<p>Bravo is designed to be used by people of all ages, including children under 13. We comply with the Children's Online Privacy Protection Act (COPPA).</p>
<h3>7.1 A guardian holds the account</h3>
<p>Accounts are created and held by an adult — a parent, guardian, or authorized caregiver. A child does not create an account, and we do not knowingly collect personal information directly from a child except through the app's communication features under the account the guardian has set up and consented to.</p>
<h3>7.2 What we collect about a child</h3>
<p>Only what Section 2 describes. That is: what you or your child <strong>enter</strong> — preferred name, interests and favorite topics, names and relationships of family and friends, places and activities, customized vocabulary, and the words and phrases composed in the app — and what the app <strong>learns</strong> from your child's answers, saved as short notes such as "favorite food: pizza."</p>
<p><strong>We want to be clear about the learning part</strong>, because it is the one thing about Bravo that a parent might not expect. The app pays attention to what your child tells people and remembers small preferences, so that it can suggest things your child actually wants to say. It saves brief notes, not recordings or transcripts. Everything it has learned is listed in Admin Toolbar → User Info Admin, marked as learned, and you can edit or delete any of it — or switch learning off, and the app will use only what you enter yourself.</p>
<p><strong>We do not condition a child's use of the app on providing more information than is reasonably necessary</strong> to generate communication suggestions. The app functions with no personalization context at all.</p>
<h3>7.3 Consent</h3>
<p>Before we collect personal information about a child, we give the guardian direct notice of what we collect, how we use it, and who receives it, and we obtain <strong>verifiable parental consent</strong>. We obtain that consent by sending a notice to the guardian's email address and requiring the guardian to confirm it from that address, followed by a second confirmation email sent after a delay so that the guardian has a further opportunity to review or withdraw the consent.</p>
<p><strong>About our AI provider.</strong> We send a child's personalization context to Google for one purpose only: generating the communication suggestions the child is asking for. Google acts solely as our service provider in support of the internal operations of Bravo. It is contractually prohibited from using the information to train its models, from disclosing it to anyone, and from using it for any other purpose, and it does not retain the information.</p>
<p><strong>You can turn this off.</strong> Bravo offers its words and phrases using AI either way — that is how the app works. What you control is whether it may also use <strong>what we know about your child</strong> to make those suggestions fit them. Turn it off and the app behaves exactly as it does now, with more general suggestions: "do you want to go outside?" rather than "do you want to go to Grandma's?" Change it at any time in Admin Toolbar → User Info Admin.</p>
<p><strong>One exception, and it is deliberate.</strong> Allergies and any physical or communication limitations you have recorded are <strong>always</strong> taken into account, even with this turned off. They are safety information, not personalization — turning this setting off should never mean Bravo starts suggesting something unsafe for your child. See Section 2.</p>
<h3>7.4 Guardian rights</h3>
<p>At any time, a parent or guardian may:</p>
<ul><li><strong>review</strong> the personal information we hold about their child;</li><li><strong>correct</strong> it;</li><li><strong>delete</strong> it, in whole or in part;</li><li><strong>withdraw consent</strong> and refuse to permit further collection or use, including withdrawing consent to AI processing while continuing to use the app; and</li><li><strong>export</strong> it in a portable format.</li></ul>
<p>Most of this is available directly in the app at Admin Toolbar → User Info Admin. You may also write to admin@talkwithbravo.com, and we will verify your identity as the account holder before acting. Deleting a child's information may make parts of the app stop working, and we will tell you which parts before you confirm.</p>
<h3>7.5 Retention of children's information — published retention policy</h3>
<p>We retain a child's personal information <strong>only as long as reasonably necessary to provide the service for which it was collected</strong>, and we do not retain it indefinitely. Specifically:</p>
<ul><li>Profile and personalization context is retained while the account is active and the guardian keeps the profile in place.</li><li>If an account is inactive for <strong>nine (9) months</strong>, we notify the account holder and then delete the child's personal information.</li><li>On deletion of a profile or account, we delete the child's personal information from our active systems within <strong>seven (7) days</strong>. Copies held in our provider's backup systems are removed within <strong>180 days</strong>, which is the maximum period our cloud provider commits to. Nothing in those backups is accessible to us or used for any purpose in the meantime.</li><li>Communication content is retained <strong>only as long as the communicator keeps it saved</strong>. Records in the activity log are deleted automatically after <strong>180 days</strong>.</li><li>Temporary context held by our AI provider to speed up suggestions (Section 5.1) expires automatically after <strong>4 hours</strong>, and <strong>we delete it immediately when a profile or account is deleted, and whenever you change or remove anything in the profile</strong>, rather than waiting for it to expire.</li></ul>
<p>We do not disclose a child's personal information to any third party except as stated in Section 5, and we do not use it for any secondary purpose.</p>
<h3>7.6 Security program</h3>
<p>We maintain a written information security program appropriate to the sensitivity of children's personal information, covering access controls, encryption, staff training, vendor assessment, and incident response. See Section 8.</p>
<h2>8. Security</h2>
<p>We protect information with encryption in transit (TLS) and at rest, role-based access controls, least-privilege staff access, audit logging of administrative access, and regular review of our cloud configuration.</p>
<p>Staff access to user content is limited to the support case you have granted and is logged.</p>
<p>No system is perfectly secure. If a breach affects your information, we will notify you and any regulator as required by applicable law, without unreasonable delay.</p>
<h2>9. Your choices and rights</h2>
<p>Whatever state you live in, we extend these to every user:</p>
<ul><li><strong>Access</strong> — get a copy of the personal information we hold about you or your child.</li><li><strong>Correct</strong> — fix anything inaccurate.</li><li><strong>Delete</strong> — remove your profile, your content, or your whole account.</li><li><strong>Export</strong> — receive your data in a portable, machine-readable format.</li><li><strong>Withdraw consent</strong> — turn off AI personalization, revoke SLP or support access, or stop using the service entirely.</li><li><strong>No discrimination</strong> — we will not degrade the free service or charge you differently for exercising any of these rights.</li></ul>
<p>Use Admin Toolbar → User Info Admin in the app, or write to admin@talkwithbravo.com. We respond within forty-five (45) days and will verify that you are the account holder first. You may authorize an agent to act for you; we will ask for proof of that authority.</p>
<p><strong>We do not sell personal information and we do not share it for cross-context behavioral advertising</strong>, so there is nothing for you to opt out of. We do not respond to Do Not Track signals because we do not track users across sites or apps.</p>
<p><strong>California residents:</strong> in the twelve months before the effective date of this policy, we collected the categories of information described in Section 2, for the purposes in Section 4, and disclosed them only to the service providers named in Section 5. We disclosed no personal information for money or other valuable consideration.</p>
<h2>10. Retention</h2>
<p>Outside of children's information (Section 7.5), we keep account information while your account is active, and profile and communication content until you delete it or close your account. After closure we delete or de-identify personal information within seven (7) days, except where we must keep something to comply with law or resolve a dispute.</p>
<h2>11. Where information is processed</h2>
<p>We are a United States company and the app is currently offered in the United States only.</p>
<p><strong>Where your information is stored.</strong> Accounts, profiles, and saved content are stored in the United States, in us-central1.</p>
<p><strong>Where suggestions are generated.</strong> Generating a suggestion is handled by Google's global Vertex AI service. That means the request may be processed at a Google facility in another country, chosen automatically based on available capacity at that moment. We tell you this because it is true, not because your information is being sent somewhere for a different purpose: the same contractual limits apply wherever the processing happens, nothing is stored outside the United States as a result, and the processing exists only to return your suggestion.</p>
<p>If we begin offering the app outside the United States, we will update this policy and put appropriate transfer safeguards in place first.</p>
<h2>12. Changes to this policy</h2>
<p>If we make a material change — particularly one that affects children's information or adds a recipient of personal information — we will notify account holders in the app or by email <strong>before</strong> it takes effect, and where the law requires it we will obtain fresh consent rather than relying on your continued use. Previous versions are archived at https://talkwithbravo.com/privacy/archive.</p>
<h2>13. Contact us</h2>
<p><strong>Talk with Bravo, LLC</strong> 10178 Foxridge Circle, Highlands Ranch, CO 80126, USA admin@talkwithbravo.com</p>
<p>For privacy questions, requests about your or your child's information, or a complaint, write to admin@talkwithbravo.com. We aim to respond within ten (10) business days.</p>`

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Privacy Policy | Talk With Bravo</title>
        <meta name="description" content="How Bravo collects, uses, and protects information — and what we never do with it." />
      </Head>

      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <span className="inline-block text-xs font-bold uppercase tracking-[0.18em] text-orange-600">
          Bravo
        </span>
        <h1 className="mt-3 text-3xl md:text-4xl font-bold text-gray-900">Privacy Policy</h1>
        <div className="mt-5 h-1 w-16 rounded-full bg-orange-600" />
        <div className="mt-6 text-lg text-gray-600">
          <p>How Bravo collects, uses, and protects information — and what we never do with it.</p>
        </div>

        <div
          className="legal mt-10 prose prose-lg max-w-none prose-headings:font-semibold prose-headings:text-gray-900 prose-h2:text-xl prose-h2:mt-10 prose-h3:text-lg prose-h3:mt-8 prose-p:text-gray-700 prose-li:text-gray-700 prose-strong:text-gray-900 prose-a:text-orange-700 prose-a:underline prose-a:underline-offset-4 hover:prose-a:text-orange-800"
          dangerouslySetInnerHTML={{ __html: CONTENT }}
        />
      </main>

      <style jsx global>{`
        .legal h1 { display: none; }
        .legal hr { margin: 2.5rem 0; border-color: #e5e7eb; }
        .legal .tbl { overflow-x: auto; border: 1px solid #e5e7eb; border-radius: 0.5rem; margin: 1.5rem 0; }
        .legal table { margin: 0; width: 100%; font-size: 0.95rem; }
        .legal thead { background: #f9fafb; }
        .legal th, .legal td { padding: 0.75rem 1rem; text-align: left; vertical-align: top; }
        .legal code { background: #f3f4f6; padding: 0.1em 0.35em; border-radius: 0.25rem; font-weight: 500; }
        .legal code::before, .legal code::after { content: none; }
      `}</style>
    </>
  )
}
